### ISSUE TITLE
Found bug with set_register8

### ISSUE THREAD

**Issue by fatrolls** [rk0der/emu_x86#1]
```
void set_register8(Emulator* emu, int index, uint8_t value)
{
  if (index < 4) {
    uint32_t r = emu->registers[index] & 0xffffff00;
    emu->registers[index] = r | (uint32_t)value;
  } else {
    uint32_t r = emu->registers[index] & 0xffff00ff;
    emu->registers[index - 4] = r | ((uint32_t)value << 8);
  }
}
```

Fixed looks like this

```
void set_register8(Emulator* emu, int index, uint8_t value)
{
  if (index < 4) {
    uint32_t r = emu->registers[index] & 0xffffff00;
    emu->registers[index] = r | (uint32_t)value;
  } else {
    uint32_t r = emu->registers[index - 4] & 0xffff00ff;
    emu->registers[index - 4] = r | ((uint32_t)value << 8);
  }
}

```

missing - 4 on the first registers array on the bottom of the else statement

Fixed also `eval_sib(..)` function it was off.

new code looks like this

```
uint32_t eval_sib(Emulator* emu, ModRM* modrm) {
    uint8_t sib = modrm->sib;
    uint8_t scale = (sib >> 6) & 0x03;   //((sib & 0xC0) >> 6); //old broken code
    uint8_t base  = sib & 0x07;          //((sib & 0x38) >> 3); //old broken code
    uint8_t index = (sib >> 3) & 0x07;   //(sib & 0x03);         //old broken code
```

Sib formula by this image match
![](http://www.swansontec.com/ssib.png)

```
  7   6   5   4   3   2   1   0
+---+---+---+---+---+---+---+---+
|  mod  |    reg    |     rm    |
+---+---+---+---+---+---+---+---+
```

changed parse_modrm 16_32 into 1 and changed

```
    modrm->mod = (code >> 6) & 0x03;     //old code  ((code & 0xC0) >> 6);
    modrm->opcode = (code >> 3) & 0x07;  //old code  ((code & 0x38) >> 3);
    modrm->rm = code & 0x07;             //old code  code & 0x07;
```

another bug where you see `modrm->mod == 5` and `modrm->mod == 6` you meant to use `modrm->rm == 5` and `modrm->rm == 6` because mod doesn't pass the value 3 it's only 2 bits.

http://download.intel.com/design/intarch/manuals/24319101.pdf Page 35 for 16 bit and page 36 for 32 bit.

I fixed more like `lea_r16_m` made it `lea_r16_r32_m` haha. added xor, or, and, stos, prefixes (buggy) still needs segments maybe? idk never worked with cpu emulators, others have it, maybe not needed.

update1: https://www.mediafire.com/?cg2q2lmfexbepz5
update2: http://www.mediafire.com/?7t601e27r348178
update3: http://www.mediafire.com/?8c3p50pp7zveo67

on update3 i fixed the memory issue.

I hope you not abandoned this project it's very good compared to other cpu emulators this is the simplest one which is best :)

it needs FPU support to be better then any other cpu emulator and still small and simple.

**Comment by octarect** [comment]
Thank you for your reporting the bugs!! 
(And I must apologize to you for my late reply :-( )

Concerning your fix of the function set_register8, I confirmed it.
I forgot to type -4 XD

> Fixed also eval_sib(..) function it was off.

Oh, now that you say it, I think so, too. Thanks :D

> changed parse_modrm 16_32 into 1 and changed

Well, you are right.
o `modrm->mod == 5`
x `modrm->rm == 5`
My mistake :(

I will see your code update1~3 and I'll make them a future reference.
(also FPU support idea)

By the way, this emulator project consists of extended code based on the following book's;
https://book.mynavi.jp/ec/products/detail/id=41347
(written in japanese)
I add a new function to the original program in the project.
But bugs often occur in code I implemented... haha
So feel free to report any bug you find, or send PR for a new function :->

P.S.

> I hope you not abandoned this project it's very good compared to other cpu emulators this is the simplest one which is best :)

Thank you for praising me :D
I'm glad to hear that.
